pluginName = EDT Metadata Favorites
providerName = Vladimir Ochakovsky
decorator.label = Избранное (EDT Metadata Favorites)
filter.name = Только избранное
filter.description = Показывать в Навигаторе только проекты и объекты метаданных из избранного
toggleFilter.name = Только избранное
toggleFilter.description = Показывать в Навигаторе только проекты и объекты метаданных из избранного
toggleFilter.tooltip = Только избранное
category.name = Избранное (EDT Metadata Favorites)
togglePin.name = Добавить/удалить из избранного
togglePin.description = Добавить выбранный проект или объект метаданных в избранное либо удалить из избранного
editorTogglePin.tooltip = Добавить или удалить открытый объект из избранного
editorTogglePin.name = Добавить/удалить открытый объект из избранного
editorTogglePin.description = Переключает состояние избранного для объекта активной карточки
editorToolbar.label = Избранное
manageFavorites.name = Избранное (управление)
manageFavorites.description = Открывает диалог массового добавления и удаления объектов метаданных в избранное
manageFavorites.menuLabel = Избранное
